authoritative;
default-lease-time 600;
max-lease-time 7200;

subnet 172.30.0.0 netmask 255.255.0.0 {
    range 172.30.0.100 172.30.0.200;
    option routers 172.30.0.1;
    option domain-name-servers 172.30.0.10;
    option domain-name "taskmanager.local";
}

